version: '3.3'

services:
  pgdrf:
    image: postgres:14.1-alpine
    environment:

      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGPORT=5433
    volumes:
      - ./data/db:/var/lib/postgresql
    expose:
      - "5433"



  app:
    build: .

    command: >
      bash -c "python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"

    ports:
      - '8000:8000'
    depends_on:
      - pgdrf
