version: '3.3'

services:
  pgdrf:
    image: postgres
    container_name: pgdrf
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
#      POSTGRES_PORT: 5432
#      POSTGRES_HOST_AUTH_METHOD: trust
#      PGDATA: ~/var/lib/postgresql/data/
    volumes:
       - ./data/db:/var/lib/postgresql
#    ports:
#      - '5432:54320'
#    healthcheck:
#      test: ['CMD-SHELL', 'pg_isready']
#      interval: 10s
#      timeout: 5s
#      retries: 5



  app:
    build: .

    command: >
      bash -c "python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"

    ports:
      - '8000:8000'
    depends_on:
      - pgdrf
