# Generated by Django 4.2.4 on 2023-08-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='lesson/', verbose_name='изображение')),
                ('video_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='ссылка на видео')),
            ],
        ),
    ]
